version: "3.5"

services:
  frontend:
    image: expense-tracker-frontend
    build: ./frontend
    ports:
      - 5000:5000
    environment:
      - BACKEND_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    image: expense-tracker-backend
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - PORT=8080
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: