name: Run init.sql Safe

on:
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Test DB connection
        run: |
          psql "host=$REAL_PG_HOST dbname=$REAL_PG_DB user=$REAL_PG_USER password=$REAL_PG_PASS" -c '\l'
        env:
          REAL_PG_HOST: ${{ secrets.POSTGRES_HOST }}
          REAL_PG_DB: ${{ secrets.POSTGRES_DB }}
          REAL_PG_USER: ${{ secrets.POSTGRES_USER }}
          REAL_PG_PASS: ${{ secrets.POSTGRES_PASSWORD }}
